const data= [
    {
      "id": 1,
      "title": "El Gran Gatsby",
      "author": "F. Scott Fitzgerald",
      "description": "La historia de Jay Gatsby, un millonario excéntrico, y su obsesión por Daisy Buchanan.",
      "isbn": "9780743273565",
      "year": "1925-01-01",
      "qualification": 5,
      "gender": "FICCIÓN",
      "imgUrl": "https://marketplace.canva.com/EAE8SCCNlvo/1/0/1003w/canva-verde-y-rosa-ciencia-ficción-portada-de-libro-SSKxUZUBOJg.jpg",
      "price": 15.99
    },
    {
      "id": 2,
      "title": "Cien años de soledad",
      "author": "Gabriel García Márquez",
      "description": "La saga de la familia Buendía en el pueblo ficticio de Macondo.",
      "isbn": "9781400071043",
      "year": "1967-01-01",
      "qualification": 4.8,
      "gender": "REALISMO MÁGICO",
      "imgUrl": "https://marketplace.canva.com/EAE8SCCNlvo/1/0/1003w/canva-verde-y-rosa-ciencia-ficción-portada-de-libro-SSKxUZUBOJg.jpg",
      "price": 18.99
    },
    {
      "id": 3,
      "title": "To Kill a Mockingbird",
      "author": "Harper Lee",
      "description": "La lucha contra la injusticia racial en un pequeño pueblo del sur de Estados Unidos.",
      "isbn": "9780061120084",
      "year": "1960-01-01",
      "qualification": 4.7,
      "gender": "NOVELA",
      "imgUrl": "https://marketplace.canva.com/EAE8SCCNlvo/1/0/1003w/canva-verde-y-rosa-ciencia-ficción-portada-de-libro-SSKxUZUBOJg.jpg",
      "price": 14.49
    },
    {
      "id": 4,
      "title": "Matar a un ruiseñor",
      "author": "Harper Lee",
      "description": "Las experiencias de una niña en un pueblo del sur de Estados Unidos durante la Gran Depresión.",
      "isbn": "9780061120083",
      "year": "1960-01-01",
      "qualification": 4.6,
      "gender": "NOVELA",
      "imgUrl": "https://marketplace.canva.com/EAE8SCCNlvo/1/0/1003w/canva-verde-y-rosa-ciencia-ficción-portada-de-libro-SSKxUZUBOJg.jpg",
      "price": 12.99
    },
    {
      "id": 5,
      "title": "1984",
      "author": "George Orwell",
      "description": "Una distopía totalitaria en la que el gobierno controla la realidad.",
      "isbn": "9780451524935",
      "year": "1949-01-01",
      "qualification": 4.9,
      "gender": "CIENCIA FICCIÓN",
      "imgUrl": "https://marketplace.canva.com/EAE8SCCNlvo/1/0/1003w/canva-verde-y-rosa-ciencia-ficción-portada-de-libro-SSKxUZUBOJg.jpg",
      "price": 16.99
    },
    {
      "id": 6,
      "title": "Rebelión en la granja",
      "author": "George Orwell",
      "description": "Una sátira política sobre una granja de animales que se sublevan contra los humanos.",
      "isbn": "9780451526342",
      "year": "1945-01-01",
      "qualification": 4.7,
      "gender": "SÁTIRA",
      "imgUrl": "https://marketplace.canva.com/EAE8SCCNlvo/1/0/1003w/canva-verde-y-rosa-ciencia-ficción-portada-de-libro-SSKxUZUBOJg.jpg",
      "price": 14.99
    },
    {
      "id": 7,
      "title": "Moby-Dick",
      "author": "Herman Melville",
      "description": "La obsesión del capitán Ahab por cazar a la ballena blanca, Moby-Dick.",
      "isbn": "9781853260087",
      "year": "1851-01-01",
      "qualification": 4.5,
      "gender": "AVENTURA",
      "imgUrl": "https://marketplace.canva.com/EAE8SCCNlvo/1/0/1003w/canva-verde-y-rosa-ciencia-ficción-portada-de-libro-SSKxUZUBOJg.jpg",
      "price": 17.49
    },
    {
      "id": 8,
      "title": "Don Quijote de la Mancha",
      "author": "Miguel de Cervantes",
      "description": "Las aventuras del caballero loco Don Quijote y su fiel escudero Sancho Panza.",
      "isbn": "9788496094041",
      "year": "1605-01-01",
      "qualification": 4.8,
      "gender": "CLÁSICO",
      "imgUrl": "https://marketplace.canva.com/EAE8SCCNlvo/1/0/1003w/canva-verde-y-rosa-ciencia-ficción-portada-de-libro-SSKxUZUBOJg.jpg",
      "price": 19.99
    },
    {
      "id": 9,
      "title": "Orgullo y prejuicio",
      "author": "Jane Austen",
      "description": "La historia de Elizabeth Bennet y el señor Darcy en la sociedad inglesa del siglo XIX.",
      "isbn": "9780486284736",
      "year": "1813-01-01",
      "qualification": 4.9,
      "gender": "ROMANCE",
      "imgUrl": "https://marketplace.canva.com/EAE8SCCNlvo/1/0/1003w/canva-verde-y-rosa-ciencia-ficción-portada-de-libro-SSKxUZUBOJg.jpg",
      "price": 13.99
    },
    {
      "id": 10,
      "title": "En busca del tiempo perdido",
      "author": "Marcel Proust",
      "description": "Una novela en siete volúmenes que explora la memoria y la introspección.",
      "isbn": "9788490061120",
      "year": "1913-01-01",
      "qualification": 4.6,
      "gender": "MODERNISMO",
      "imgUrl": "https://marketplace.canva.com/EAE8SCCNlvo/1/0/1003w/canva-verde-y-rosa-ciencia-ficción-portada-de-libro-SSKxUZUBOJg.jpg",
      "price" : 15.99
    },
    {
      "id": 11,
      "title": "Crimen y castigo",
      "author": "Fiodor Dostoievski",
      "description": "La historia de un estudiante que comete un asesinato y luego lucha con su conciencia.",
      "isbn": "9788484035271",
      "year": "1866-01-01",
      "qualification": 4.7,
      "gender": "NOVELA",
      "imgUrl": "https://marketplace.canva.com/EAE8SCCNlvo/1/0/1003w/canva-verde-y-rosa-ciencia-ficción-portada-de-libro-SSKxUZUBOJg.jpg",
      "price": 16.99
    },
    {
      "id": 12,
      "title": "El retrato de Dorian Gray",
      "author": "Oscar Wilde",
      "description": "Un joven llamado Dorian Gray conserva su juventud mientras su retrato envejece y muestra sus pecados.",
      "isbn": "9788496083144",
      "year": "1890-01-01",
      "qualification": 4.5,
      "gender": "NOVELA",
      "imgUrl": "https://marketplace.canva.com/EAE8SCCNlvo/1/0/1003w/canva-verde-y-rosa-ciencia-ficción-portada-de-libro-SSKxUZUBOJg.jpg",
      "price": 14.99
    },
    {
      "id": 13,
      "title": "Cien años de soledad",
      "author": "Gabriel García Márquez",
      "description": "La saga de la familia Buendía en el pueblo ficticio de Macondo.",
      "isbn": "9781400071043",
      "year": "1967-01-01",
      "qualification": 4.8,
      "gender": "REALISMO MÁGICO",
      "imgUrl": "https://marketplace.canva.com/EAE8SCCNlvo/1/0/1003w/canva-verde-y-rosa-ciencia-ficción-portada-de-libro-SSKxUZUBOJg.jpg",
      "price": 18.99
    },
    {
      "id": 14,
      "title": "El nombre de la rosa",
      "author": "Umberto Eco",
      "description": "Un monje franciscano investiga una serie de asesinatos en una abadía en el siglo XIV.",
      "isbn": "9788447301605",
      "year": "1980-01-01",
      "qualification": 4.6,
      "gender": "MISTERIO",
      "imgUrl": "https://marketplace.canva.com/EAE8SCCNlvo/1/0/1003w/canva-verde-y-rosa-ciencia-ficción-portada-de-libro-SSKxUZUBOJg.jpg",
      "price": 16.99
    },
    {
      "id": 15,
      "title": "La sombra del viento",
      "author": "Carlos Ruiz Zafón",
      "description": "Un joven busca la verdad detrás de un libro en el Cementerio de los Libros Olvidados en Barcelona.",
      "isbn": "9788408079545",
      "year": "2001-01-01",
      "qualification": 4.7,
      "gender": "MISTERIO",
      "imgUrl": "https://marketplace.canva.com/EAE8SCCNlvo/1/0/1003w/canva-verde-y-rosa-ciencia-ficción-portada-de-libro-SSKxUZUBOJg.jpg",
      "price": 15.99
    },
    {
      "id": 16,
      "title": "Harry Potter y la piedra filosofal",
      "author": "J.K. Rowling",
      "description": "El comienzo de las aventuras de Harry Potter en el mundo mágico de Hogwarts.",
      "isbn": "9788478884451",
      "year": "1997-01-01",
      "qualification": 4.9,
      "gender": "FANTASÍA",
      "imgUrl": "https://marketplace.canva.com/EAE8SCCNlvo/1/0/1003w/canva-verde-y-rosa-ciencia-ficción-portada-de-libro-SSKxUZUBOJg.jpg",
      "price": 12.99
    },
    {
      "id": 17,
      "title": "El Hobbit",
      "author": "J.R.R. Tolkien",
      "description": "El viaje de Bilbo Bolsón para recuperar un tesoro custodiado por un dragón.",
      "isbn": "9788445073803",
      "year": "1937-01-01",
      "qualification": 4.8,
      "gender": "FANTASÍA",
      "imgUrl": "https://marketplace.canva.com/EAE8SCCNlvo/1/0/1003w/canva-verde-y-rosa-ciencia-ficción-portada-de-libro-SSKxUZUBOJg.jpg",
      "price": 13.99
    },
    {
      "id": 18,
      "title": "1984",
      "author": "George Orwell",
      "description": "Una distopía totalitaria en la que el gobierno controla la realidad.",
      "isbn": "9780451524935",
      "year": "1949-01-01",
      "qualification": 4.9,
      "gender": "CIENCIA FICCIÓN",
      "imgUrl": "https://marketplace.canva.com/EAE8SCCNlvo/1/0/1003w/canva-verde-y-rosa-ciencia-ficción-portada-de-libro-SSKxUZUBOJg.jpg",
      "price": 16.99
    },
    {
      "id": 19,
      "title": "Rebelión en la granja",
      "author": "George Orwell",
      "description": "Una sátira política sobre una granja de animales que se sublevan contra los humanos.",
      "isbn": "9780451526342",
      "year": "1945-01-01",
      "qualification": 4.7,
      "gender": "SÁTIRA",
      "imgUrl": "https://marketplace.canva.com/EAE8SCCNlvo/1/0/1003w/canva-verde-y-rosa-ciencia-ficción-portada-de-libro-SSKxUZUBOJg.jpg",
      "price": 14.99
    },
    {
      "id": 20,
      "title": "Moby-Dick",
      "author": "Herman Melville",
      "description": "La obsesión del capitán Ahab por cazar a la ballena blanca, Moby-Dick.",
      "isbn": "9781853260087",
      "year": "1851-01-01",
      "qualification": 4.5,
      "gender": "AVENTURA",
      "imgUrl": "https://marketplace.canva.com/EAE8SCCNlvo/1/0/1003w/canva-verde-y-rosa-ciencia-ficción-portada-de-libro-SSKxUZUBOJg.jpg",
      "price": 17.49
    },
    {
      "id": 21,
      "title": "Don Quijote de la Mancha",
      "author": "Miguel de Cervantes",
      "description": "Las aventuras del caballero loco Don Quijote y su fiel escudero Sancho Panza.",
      "isbn": "9788496094041",
      "year": "1605-01-01",
      "qualification": 4.8,
      "gender": "CLÁSICO",
      "imgUrl": "https://www.ejemplo.com/imagenes/donquijotepic.jpg",
      "price": 19.99
    },
    {
      "id": 22,
      "title": "Orgullo y prejuicio",
      "author": "Jane Austen",
      "description": "La historia de Elizabeth Bennet y el señor Darcy en la sociedad inglesa del siglo XIX.",
      "isbn": "9780486284736",
      "year": "1813-01-01",
      "qualification": 4.9,
      "gender": "ROMANCE",
      "imgUrl": "https://www.ejemplo.com/imagenes/orgulloyprejpic.jpg",
      "price": 13.99
    },
    {
      "id": 23,
      "title": "En busca del tiempo perdido",
      "author": "Marcel Proust",
      "description": "Una novela en siete volúmenes que explora la memoria y la introspección.",
      "isbn": "9788490061120",
      "year": "1913-01-01",
      "qualification": 4.6,
      "gender": "MODERNISMO",
      "imgUrl": "https://www.ejemplo.com/imagenes/enbuscatiempop.jpg",
      "price": 22.99
    },
    {
      "id": 24,
      "title": "Crimen y castigo",
      "author": "Fiodor Dostoievski",
      "description": "La historia de un estudiante que comete un asesinato y luego lucha con su conciencia.",
      "isbn": "9788484035271",
      "year": "1866-01-01",
      "qualification": 4.7,
      "gender": "NOVELA",
      "imgUrl": "https://www.ejemplo.com/imagenes/crimencastigopic.jpg",
      "price": 16.99
    },
    {
      "id": 25,
      "title": "El retrato de Dorian Gray",
      "author": "Oscar Wilde",
      "description": "Un joven llamado Dorian Gray conserva su juventud mientras su retrato envejece y muestra sus pecados.",
      "isbn": "9788496083144",
      "year": "1890-01-01",
      "qualification": 4.5,
      "gender": "NOVELA",
      "imgUrl": "https://www.ejemplo.com/imagenes/doriangraypic.jpg",
      "price": 14.99
    },
    {
      "id": 26,
      "title": "Cien años de soledad",
      "author": "Gabriel García Márquez",
      "description": "La saga de la familia Buendía en el pueblo ficticio de Macondo.",
      "isbn": "9781400071043",
      "year": "1967-01-01",
      "qualification": 4.8,
      "gender": "REALISMO MÁGICO",
      "imgUrl": "https://www.ejemplo.com/imagenes/ciensoledadpic.jpg",
      "price": 18.99
    },
    {
      "id": 27,
      "title": "El nombre de la rosa",
      "author": "Umberto Eco",
      "description": "Un monje franciscano investiga una serie de asesinatos en una abadía en el siglo XIV.",
      "isbn": "9788447301605",
      "year": "1980-01-01",
      "qualification": 4.6,
      "gender": "MISTERIO",
      "imgUrl": "https://www.ejemplo.com/imagenes/nombrosapic.jpg",
      "price": 16.99
    },
    {
      "id": 28,
      "title": "La sombra del viento",
      "author": "Carlos Ruiz Zafón",
      "description": "Un joven busca la verdad detrás de un libro en el Cementerio de los Libros Olvidados en Barcelona.",
      "isbn": "9788408079545",
      "year": "2001-01-01",
      "qualification": 4.7,
      "gender": "MISTERIO",
      "imgUrl": "https://www.ejemplo.com/imagenes/sombravientopic.jpg",
      "price": 15.99
    },
    {
      "id": 29,
      "title": "Harry Potter y la piedra filosofal",
      "author": "J.K. Rowling",
      "description": "El comienzo de las aventuras de Harry Potter en el mundo mágico de Hogwarts.",
      "isbn": "9788478884451",
      "year": "1997-01-01",
      "qualification": 4.9,
      "gender": "FANTASÍA",
      "imgUrl": "https://www.ejemplo.com/imagenes/harrypotter1pic.jpg",
      "price": 12.99
    },
    {
      "id": 30,
      "title": "El Hobbit",
      "author": "J.R.R. Tolkien",
      "description": "El viaje de Bilbo Bolsón para recuperar un tesoro custodiado por un dragón.",
      "isbn": "9788445073803",
      "year": "1937-01-01",
      "qualification": 4.8,
      "gender": "FANTASÍA",
      "imgUrl": "https://www.ejemplo.com/imagenes/elhobbitpic.jpg",
      "price": 13.99
    }
  ]
  
  export default data